### PR TITLE
Updated Personal Data

### PR DESCRIPTION
**Pull request by james-jasvin**
Changed images and Excel sheets to remove personal information. Have a look and see whether everything is in order

### CODE REVIEW

**Comment by mohdabbas378** [comment]
Nice!

Did you test this out?

**Review by mohdabbas378 — APPROVED** [review]

**Comment by james-jasvin** [comment]
Ofc not. I just put all my effort into finding proper Face Recognition dataset and stumbled on this goldmine of Simpson's characters, then just spent time manually editing all excel sheets and removing names and making everything of proper size. I'll be surprised if this even works.

**Comment by james-jasvin** [comment]
So do I Merge Pull Request?

**Comment by mohdabbas378** [comment]
This may fail if we've hardcoded some path somewhere :laughing:

**Comment by james-jasvin** [comment]
> 
> 
> This may fail if we've hardcoded some path somewhere 😆

I don't think we have. I had a look through the code before embarking on this manual labour journey. So should I merge branch then?

**Comment by mohdabbas378** [comment]
Yepp go for it!
We also need to update the readme 😅

**Comment by james-jasvin** [comment]
well that's something for you then. I'm done playing this old game.
Actually I think I've got something in the readme of my personal repo but its not that descriptive or anything. So there's that.
Anyways I'm merging.

**Pull request merged**
